server:
  port: 7003
eureka:
  instance:
    hostname: localhost #服务端名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册
    fetch-registry: false #如果为false则表示自己为注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #表示监控页面

#eureka配置