server:
  port: 8002


spring:
  application:
    name: sprinigcloud-provider-dept #三个服务名字一样是实现负载均衡的前提
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&&useSSL=false&&useUnicode=true&&characterEncoding=UTF-8
    password: 123456
    username: root
# eureka配置 服务注册到哪里
eureka:
  client:
    service-url: #发布到注册中心中
      #defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept-8002 #修改eureka上默认描述信息



