server:
  port: 8001
mybatis:
  type-aliases-package: com.lu.springcloud.pojo
  mapper-location: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: sprinigcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&&useSSL=false&&useUnicode=true&&characterEncoding=UTF-8
    password: 123456
    username: root

